from .com_like import com_like
from .edit_acc import edit_acc
from .liked import new_like
from .new_user import new_user
from .serch_acc import search_acc
from .serch_like import search_like
from  .serch_anket import search_anket
from .write_None import write_None
from .mylike import mylike